FROM node:20-alpine
WORKDIR /app


COPY ./backend/package.json ./
COPY ./backend/package-lock.json ./

#copy whole backend folder
COPY ./backend ./

RUN npm install

EXPOSE 3306
EXPOSE 5000

CMD ["npm", "run", "start"]
